# server config
server:
  port: 8888
  servlet:
    session:
      timeout: 360000s
    # 인코딩 UTF-8로 설정
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  name : client
  profiles:
    active: dev
    web:
      resources:
        static-locations: file:src/main/resources/static/
  cloud:
    config:
      server:
        git:
          uri:

app:
  oauth2:
    authorizedRedirectUris: http://localhost:8888/oauth2/redirect
  auth:
    tokenSecret: adjlaksjdlkasjdlkajwkljelk12j3lk1j2lk3j1lk23jlkdjalksje12lk3jl1k2j3lk12j3kjaslkjdlkasjd12312dasdasd
    tokenExpirationMsec: 1800000
  cors:
    allowedOrigins: http://localhost:8888